apiVersion: v1
kind: Pod
metadata:
  name: tolerations-4
  labels:
    purpose: "tolerations-demo"
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "cpu"
    effect: "NoExecute"

     